param()

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$publicRoot = Join-Path $projectRoot 'public'

function Write-SpanishPage {
  param(
    [Parameter(Mandatory)] [string] $Source,
    [Parameter(Mandatory)] [string] $Destination,
    [Parameter(Mandatory)] [System.Collections.Specialized.OrderedDictionary] $Replacements
  )

  $html = [System.IO.File]::ReadAllText($Source)
  foreach ($entry in $Replacements.GetEnumerator()) {
    if (-not $html.Contains([string] $entry.Key)) {
      throw "Spanish build source text was not found in $Source`: $($entry.Key)"
    }
    $html = $html.Replace([string] $entry.Key, [string] $entry.Value)
  }

  $destinationDirectory = Split-Path -Parent $Destination
  [System.IO.Directory]::CreateDirectory($destinationDirectory) | Out-Null
  [System.IO.File]::WriteAllText($Destination, $html, [System.Text.UTF8Encoding]::new($false))
}

$shared = [ordered]@{
  '<html lang="en">' = '<html lang="es-HN">'
  '<meta property="og:locale" content="en_US" />' = ('<meta property="og:locale" content="es_HN" />' + [Environment]::NewLine + '  <meta property="og:locale:alternate" content="en_US" />')
  '<a class="skip-link" href="#main">Skip to main content</a>' = '<a class="skip-link" href="#main">Saltar al contenido principal</a>'
  'aria-label="Primary navigation"' = 'aria-label="Navegación principal"'
  '<span class="sr-only">Open navigation</span>' = '<span class="sr-only">Abrir navegación</span>'
  '>Overview</' = '>Resumen</'
  '>Gallery</' = '>Galería</'
  '>Activities</' = '>Actividades</'
  '>Availability</' = '>Disponibilidad</'
  '<strong>Explore more</strong>' = '<strong>Conozca más</strong>'
  'aria-label="More stay guides"' = 'aria-label="Más guías para su estadía"'
  '>Pristine Bay vacation rental</a>' = '>Alquiler vacacional en Pristine Bay</a>'
  '>Roatán golf and diving</a>' = '>Golf y buceo en Roatán</a>'
  '>Villa and amenities</a>' = '>Villa y comodidades</a>'
  '<span>Contact them for more information, booking follow-up, payment, and scheduling.</span>' = '<span>Contáctelos para más información y para dar seguimiento a su reservación, pago y fechas.</span>'
  'data-language-switch="es" aria-label="Ver esta página en español">ES</a>' = 'data-language-switch="en" aria-label="Ver esta página en inglés">EN</a>'
}

$homePage = [ordered]@{}
foreach ($entry in $shared.GetEnumerator()) { $homePage.Add($entry.Key, $entry.Value) }
$homePage.Add('<title>Pristine Bay Roatán Vacation Rental | 1111 Pearl Court</title>', '<title>Alquiler vacacional en Pristine Bay, Roatán | 1111 Pearl Court</title>')
$homePage.Add('content="Stay at 1111 Pearl Court, a private two-suite vacation villa with an infinity pool inside gated Pristine Bay, near Roatán golf and scuba diving."', 'content="Hospédese en 1111 Pearl Court, una villa privada para cuatro con piscina infinita dentro de Pristine Bay, cerca del golf y el buceo en Roatán."')
$homePage.Add('<link rel="canonical" href="https://staypristinebay.com/" />', '<link rel="canonical" href="https://staypristinebay.com/es/" />')
$homePage.Add('<meta property="og:url" content="https://staypristinebay.com/" />', '<meta property="og:url" content="https://staypristinebay.com/es/" />')
$homePage.Add('content="1111 Pearl Court · Pristine Bay Roatán Vacation Villa"', 'content="1111 Pearl Court · Villa vacacional en Pristine Bay, Roatán"')
$homePage.Add('content="Golf, dive, and explore Roatán from a private two-suite villa with an infinity pool inside gated Pristine Bay."', 'content="Disfrute el golf, el buceo y Roatán desde una villa privada para cuatro con piscina infinita dentro de Pristine Bay."')
$homePage.Add('content="1111 Pearl Court vacation villa and tropical garden in Pristine Bay, Roatán"', 'content="Villa vacacional 1111 Pearl Court y jardín tropical en Pristine Bay, Roatán"')
$homePage.Add('"url": "https://staypristinebay.com/",', ('"url": "https://staypristinebay.com/es/",' + [Environment]::NewLine + '    "inLanguage": "es-HN",'))
$homePage.Add('"description": "A private two-suite vacation villa with an infinity pool inside the gated Pristine Bay community in Roatán, Honduras, near the Black Pearl Golf Course and scuba diving."', '"description": "Villa vacacional privada para cuatro personas, con dos suites y piscina infinita dentro de la comunidad cerrada Pristine Bay en Roatán, Honduras, cerca del campo de golf Black Pearl y del buceo."')
$homePage.Add('"name": "Private infinity pool"', '"name": "Piscina infinita privada"')
$homePage.Add('"name": "Gated community"', '"name": "Comunidad cerrada"')
$homePage.Add('"name": "Air conditioning"', '"name": "Aire acondicionado"')
$homePage.Add('"name": "Full kitchen"', '"name": "Cocina completa"')
$homePage.Add('"name": "Laundry"', '"name": "Lavandería"')
$homePage.Add('aria-label="Pristine Bay Villa home"', 'aria-label="Inicio de Villa Pristine Bay"')
$homePage.Add('href="/es/" hreflang="es" lang="es" data-language-switch="en"', 'href="/" hreflang="en" lang="en" data-language-switch="en"')
$homePage.Add('alt="Garden-side view of 1111 Pearl Court with palms, patios, and tropical landscaping"', 'alt="Vista del jardín de 1111 Pearl Court con palmeras, terrazas y vegetación tropical"')
$homePage.Add('aria-label="Open the property photo gallery"', 'aria-label="Abrir la galería de fotos de la propiedad"')
$homePage.Add('>Garden-side villa and patios</div>', '>Villa y terrazas junto al jardín</div>')
$homePage.Add('Golf · Dive · Unwind in Roatán', 'Golf · Buceo · Descanso en Roatán')
$homePage.Add('<h1><span class="title-line">Your island days</span><span class="title-line">start here.</span></h1>', '<h1><span class="title-line">Sus días en la isla</span><span class="title-line">comienzan aquí.</span></h1>')
$homePage.Add('In the gated Pristine Bay community, steps from the Black Pearl Golf Course and close to world-class scuba diving. Your private villa has an infinity pool and room for four.', 'Dentro de la comunidad cerrada Pristine Bay, a pasos del campo de golf Black Pearl y cerca de buceo de clase mundial. Su villa privada tiene piscina infinita y espacio para cuatro personas.')
$homePage.Add('>Explore the area</button>', '>Conozca los alrededores</button>')
$homePage.Add('>Check availability</button>', '>Consultar disponibilidad</button>')
$homePage.Add('aria-label="Stay highlights"', 'aria-label="Lo mejor de la estadía"')
$homePage.Add('<strong>Inside gated Pristine Bay</strong><small>A private villa, infinity pool, and room for four</small><em>Explore Pristine Bay →</em>', '<strong>Dentro de Pristine Bay</strong><small>Villa privada, piscina infinita y espacio para cuatro</small><em>Conozca Pristine Bay →</em>')
$homePage.Add('<strong>Golf &amp; diving close by</strong><small>Steps from Black Pearl and near the Scuba Shop</small><em>See activities →</em>', '<strong>Golf y buceo muy cerca</strong><small>A pasos de Black Pearl y cerca de Scuba Shop</small><em>Ver actividades →</em>')
$homePage.Add('Beyond the front door', 'Más allá de la puerta')
$homePage.Add('Come for the villa.<br />Book for the island.', 'Venga por la villa.<br />Reserve por la isla.')
$homePage.Add('Spend the morning on the fairway, head below the surface in the afternoon, then enjoy dining and island sunsets. Everything you need is right here in Pristine Bay.', 'Pase la mañana en el campo de golf, sumérjase por la tarde y luego disfrute la gastronomía y los atardeceres isleños. Todo lo que necesita está aquí mismo, en Pristine Bay.')
$homePage.Add('alt="Aerial view of the Black Pearl Golf Course and Caribbean coastline at Pristine Bay"', 'alt="Vista aérea del campo de golf Black Pearl y la costa caribeña en Pristine Bay"')
$homePage.Add('<small>Golf · Dining · Activities</small><strong>Experience Pristine Bay</strong><em>Visit pristinebay.com ↗</em>', '<small>Golf · Gastronomía · Actividades</small><strong>Disfrute Pristine Bay</strong><em>Visitar pristinebay.com ↗</em>')
$homePage.Add('alt="The Scuba Shop at Pristine Bay beside the Caribbean shore"', 'alt="Scuba Shop en Pristine Bay, junto a la costa caribeña"')
$homePage.Add('<small>Diving · Snorkelling · Training</small><strong>Discover the Scuba Shop</strong><em>Visit scuba.shop ↗</em>', '<small>Buceo · Esnórquel · Capacitación</small><strong>Conozca Scuba Shop</strong><em>Visitar scuba.shop ↗</em>')
$homePage.Add('Activities, reservations, hours, fees, and community amenity access are arranged separately. Confirm current details with each provider or the property manager.', 'Las actividades, reservaciones, horarios, tarifas y el acceso a las amenidades de la comunidad se coordinan por separado. Confirme los detalles vigentes con cada proveedor o con la administración de la propiedad.')
$homePage.Add('Your private base', 'Su espacio privado')
$homePage.Add('Everything you need.<br />Nothing to overthink.', 'Todo lo que necesita.<br />Sin complicaciones.')
$homePage.Add('The villa keeps the details simple: private space for four, easy indoor-outdoor living, and the everyday comforts that let you settle in.', 'La villa hace todo más sencillo: espacio privado para cuatro, ambientes interiores y exteriores conectados, y las comodidades diarias para sentirse a gusto.')
$homePage.Add('See live availability', 'Ver disponibilidad en vivo')
$homePage.Add('Two complete<br />king suites', 'Dos suites completas<br />con cama king')
$homePage.Add('Each upstairs bedroom has a full ensuite, walk-in closet, and furnished private balcony. The villa sleeps four, with an additional powder room on the main level.', 'Cada dormitorio del piso superior tiene baño privado completo, vestidor y balcón privado amueblado. La villa aloja a cuatro personas y cuenta con un medio baño adicional en la planta principal.')
$homePage.Add('View primary suite photos →', 'Ver fotos de la suite principal →')
$homePage.Add('Pool, patios &amp;<br />everyday comfort', 'Piscina, terrazas y<br />comodidad diaria')
$homePage.Add('Open-plan living, dining, and a fully equipped kitchen flow outside to the private infinity pool. Air conditioning, Wi-Fi, laundry, televisions, and essential appliances are included.', 'La sala, el comedor y la cocina totalmente equipada se integran con el exterior y la piscina infinita privada. Incluye aire acondicionado, Wi-Fi, lavandería, televisores y electrodomésticos esenciales.')
$homePage.Add('View pool &amp; outdoor photos →', 'Ver fotos de la piscina y exteriores →')
$homePage.Add('aria-label="Villa capacity and layout"', 'aria-label="Capacidad y distribución de la villa"')
$homePage.Add('</strong> bedrooms', '</strong> dormitorios')
$homePage.Add('</strong> bathrooms', '</strong> baños')
$homePage.Add('</strong> guests', '</strong> huéspedes')
$homePage.Add('</strong> night minimum*', '</strong> noches como mínimo*')
$homePage.Add('*Confirm current minimum stay and terms when booking.', '*Confirme la estadía mínima y las condiciones vigentes al reservar.')
$homePage.Add('The visual tour', 'Recorrido visual')
$homePage.Add('Explore every space.', 'Conozca cada espacio.')
$homePage.Add('Browse the villa and grounds through our curated photo collection. Use the filters to focus on the spaces that matter most to you.', 'Recorra la villa y sus alrededores en nuestra selección de fotografías. Use los filtros para ver los espacios que más le interesan.')
$homePage.Add('aria-label="Filter photos"', 'aria-label="Filtrar fotos"')
$homePage.Add('>All</button>', '>Todas</button>')
$homePage.Add('>Pool &amp; outdoor</button>', '>Piscina y exteriores</button>')
$homePage.Add('>Main level</button>', '>Planta principal</button>')
$homePage.Add('>Primary suite</button>', '>Suite principal</button>')
$homePage.Add('>Guest suite</button>', '>Suite de huéspedes</button>')
$homePage.Add('>Show photos</label>', '>Mostrar fotos</label>')
$homePage.Add('>All photos (57)</option>', '>Todas las fotos (57)</option>')
$homePage.Add('>Pool &amp; outdoor (13)</option>', '>Piscina y exteriores (13)</option>')
$homePage.Add('>Main level (13)</option>', '>Planta principal (13)</option>')
$homePage.Add('>Primary suite (10)</option>', '>Suite principal (10)</option>')
$homePage.Add('>Guest suite (8)</option>', '>Suite de huéspedes (8)</option>')
$homePage.Add('alt="Villa and private pool from the fairway side"', 'alt="Villa y piscina privada vistas desde el campo de golf"')
$homePage.Add('aria-label="Previous photo"', 'aria-label="Foto anterior"')
$homePage.Add('aria-label="Next photo"', 'aria-label="Foto siguiente"')
$homePage.Add('>Open &amp; zoom ', '>Abrir y ampliar ')
$homePage.Add('>Aerial exterior</span>', '>Vista aérea exterior</span>')
$homePage.Add('>Villa and private pool from the fairway side</strong>', '>Villa y piscina privada vistas desde el campo de golf</strong>')
$homePage.Add('<strong>Photo collection</strong>', '<strong>Colección de fotos</strong>')
$homePage.Add('>57 photos</span>', '>57 fotos</span>')
$homePage.Add('aria-label="Property photo thumbnails"', 'aria-label="Miniaturas de fotos de la propiedad"')
$homePage.Add('Activities &amp; amenities,<br />all around you.', 'Actividades y amenidades,<br />a su alrededor.')
$homePage.Add('<p class="eyebrow">Explore the area</p>', '<p class="eyebrow">Explore los alrededores</p>')
$homePage.Add('Roatán Villa at Pristine Bay places you close to championship golf, world-class diving, beaches, dining, breweries, and memorable island outings.', 'Villa Roatán en Pristine Bay lo acerca al golf de campeonato, buceo de clase mundial, playas, restaurantes, cervecerías y paseos inolvidables por la isla.')
$homePage.Add('aria-label="Explore activity categories"', 'aria-label="Explorar categorías de actividades"')
$homePage.Add('<strong>Golf</strong><small>Championship course moments away.</small><em>Explore golf →</em>', '<strong>Golf</strong><small>Campo de campeonato a pocos minutos.</small><em>Conocer el golf →</em>')
$homePage.Add('<strong>Diving</strong><small>Reefs, wrecks, and clear Caribbean water.</small><em>Explore diving →</em>', '<strong>Buceo</strong><small>Arrecifes, naufragios y aguas cristalinas del Caribe.</small><em>Conocer el buceo →</em>')
$homePage.Add('<strong>Beaches</strong><small>White sand and turquoise sea.</small><em>Explore beaches →</em>', '<strong>Playas</strong><small>Arena blanca y mar turquesa.</small><em>Conocer las playas →</em>')
$homePage.Add('<strong>Dining</strong><small>Island flavours and ocean views.</small><em>Explore dining →</em>', '<strong>Gastronomía</strong><small>Sabores isleños y vistas al mar.</small><em>Conocer restaurantes →</em>')
$homePage.Add('<strong>Breweries</strong><small>Local craft and laid-back island stops.</small><em>Visit Roatán Island Brewing →</em>', '<strong>Cervecerías</strong><small>Cerveza artesanal local y ambiente isleño.</small><em>Visitar Roatán Island Brewing →</em>')
$homePage.Add('<strong>Family Stops</strong><small>Fun island outings for all ages.</small><em>Explore family stops →</em>', '<strong>Paseos familiares</strong><small>Experiencias divertidas para todas las edades.</small><em>Conocer paseos familiares →</em>')
$homePage.Add('alt="Black Pearl Golf Course beside the Caribbean"', 'alt="Campo de golf Black Pearl junto al Caribe"')
$homePage.Add('alt="Scuba diver exploring a tropical coral reef"', 'alt="Buzo explorando un arrecife de coral tropical"')
$homePage.Add('alt="Sandy shoreline at Pristine Bay"', 'alt="Costa de arena en Pristine Bay"')
$homePage.Add('alt="Open-air dining by the Caribbean Sea"', 'alt="Comedor al aire libre junto al mar Caribe"')
$homePage.Add('alt="Local craft beer being poured"', 'alt="Cerveza artesanal local recién servida"')
$homePage.Add('alt="Colourful macaws in a tropical setting"', 'alt="Guacamayas coloridas en un entorno tropical"')
$homePage.Add('aria-label="Interactive map of activities and amenities around Roatán"', 'aria-label="Mapa interactivo de actividades y amenidades en Roatán"')
$homePage.Add('>Explore Roatán in Google Maps ↗</a>', '>Explorar Roatán en Google Maps ↗</a>')
$homePage.Add('Nearby experiences', 'Experiencias cercanas')
$homePage.Add('<span>Diving</span>', '<span>Buceo</span>')
$homePage.Add('<span>Beach club</span>', '<span>Club de playa</span>')
$homePage.Add('<span>Beach</span>', '<span>Playa</span>')
$homePage.Add('<span>Dining</span>', '<span>Restaurantes</span>')
$homePage.Add('<span>Brewery</span>', '<span>Cervecería</span>')
$homePage.Add('<span>Attraction</span>', '<span>Atracción</span>')
$homePage.Add('<span>Family stop</span>', '<span>Paseo familiar</span>')
$homePage.Add('Markers are approximate. Open a listing for current directions.', 'La ubicación de los marcadores es aproximada. Abra un lugar para obtener indicaciones actualizadas.')
$homePage.Add('A day nearby', 'Un día por los alrededores')
$homePage.Add('Ideas for how to spend your time on island.', 'Ideas para aprovechar su tiempo en la isla.')
$homePage.Add('Pristine Bay morning', 'Mañana en Pristine Bay')
$homePage.Add('Villa to Black Pearl, then onward to the Beach Club.', 'De la villa a Black Pearl y luego al Beach Club.')
$homePage.Add('Reef &amp; sunset', 'Arrecife y atardecer')
$homePage.Add('Start at the Scuba Shop, then continue to West Bay and West End.', 'Comience en Scuba Shop y luego continúe hacia West Bay y West End.')
$homePage.Add('Trails &amp; local pours', 'Senderos y cerveza local')
$homePage.Add("Pair Roatán Island Brewing Co. with Carambola’s garden trails.", 'Combine Roatán Island Brewing Co. con los senderos de Carambola Botanical Gardens.')
$homePage.Add('alt="Pristine Bay shoreline"', 'alt="Costa de Pristine Bay"')
$homePage.Add('alt="Tropical scuba diving"', 'alt="Buceo tropical"')
$homePage.Add('alt="Craft beer at a brewery"', 'alt="Cerveza artesanal en una cervecería"')
$homePage.Add('<strong>West End Dining</strong>', '<strong>Restaurantes de West End</strong>')
$homePage.Add('Open itinerary →', 'Abrir itinerario →')
$homePage.Add("What’s close", 'Qué hay cerca')
$homePage.Add('Conveniences and amenities that make your stay effortless.', 'Servicios y amenidades para una estadía sin complicaciones.')
$homePage.Add('<strong>Pool &amp; beach access</strong><p>Private pool at the villa and community amenities subject to current access.</p>', '<strong>Acceso a piscina y playa</strong><p>Piscina privada en la villa y amenidades comunitarias sujetas al acceso vigente.</p>')
$homePage.Add('<strong>Dining</strong><p>From casual bites to destination dining across the island.</p>', '<strong>Restaurantes</strong><p>Desde opciones informales hasta restaurantes especiales por toda la isla.</p>')
$homePage.Add('<strong>Shopping &amp; essentials</strong><p>Groceries, shops, and pharmacies are available around Roatán.</p>', '<strong>Compras y artículos esenciales</strong><p>Hay supermercados, tiendas y farmacias en distintos puntos de Roatán.</p>')
$homePage.Add('<strong>Excursions &amp; tours</strong><p>Book fishing, snorkelling, catamaran sails, and island tours.</p>', '<strong>Excursiones y tours</strong><p>Reserve pesca, esnórquel, paseos en catamarán y recorridos por la isla.</p>')
$homePage.Add('Times, access, reservations, and availability may vary. Confirm details directly with providers or the property manager. Category photography is representative.', 'Los horarios, el acceso, las reservaciones y la disponibilidad pueden variar. Confirme los detalles directamente con los proveedores o con la administración de la propiedad. Las fotografías de las categorías son ilustrativas.')
$homePage.Add('The setting', 'El entorno')
$homePage.Add('Pristine Bay,<br />island pace.', 'Pristine Bay,<br />al ritmo de la isla.')
$homePage.Add('A gated coastal community centered around the Black Pearl Golf Course, with easy access to world-class diving, shoreline, and relaxed island living.', 'Una comunidad costera cerrada alrededor del campo de golf Black Pearl, con fácil acceso a buceo de clase mundial, la costa y el estilo de vida relajado de la isla.')
$homePage.Add('aria-label="Pristine Bay highlights"', 'aria-label="Lo mejor de Pristine Bay"')
$homePage.Add('>Gated community</span>', '>Comunidad cerrada</span>')
$homePage.Add('>Diving &amp; shoreline</span>', '>Buceo y costa</span>')
$homePage.Add('>Relaxed island living</span>', '>Vida isleña relajada</span>')
$homePage.Add('Your browser does not support embedded video.', 'Su navegador no permite reproducir este video.')
$homePage.Add('>Full screen</button>', '>Pantalla completa</button>')
$homePage.Add("<strong>Dive into Roatán</strong><p>Coastline, turquoise water, and the island’s adventurous side.</p>", '<strong>Sumérjase en Roatán</strong><p>Costa, agua turquesa y el lado aventurero de la isla.</p>')
$homePage.Add('<strong>Arrive, then explore</strong><p>A quick look at getting here and the experiences waiting nearby.</p>', '<strong>Llegue y empiece a explorar</strong><p>Un vistazo rápido a cómo llegar y a las experiencias cercanas.</p>')
$homePage.Add('aria-label="Interactive map of the villa and nearby Pristine Bay amenities"', 'aria-label="Mapa interactivo de la villa y amenidades cercanas en Pristine Bay"')
$homePage.Add('>Open 1111 Pearl Court in Google Maps ↗</a>', '>Abrir 1111 Pearl Court en Google Maps ↗</a>')
$homePage.Add('On the map', 'En el mapa')
$homePage.Add('More to do,<br />right in Pristine Bay.', 'Más por hacer,<br />aquí mismo en Pristine Bay.')
$homePage.Add('The villa, golf course, Beach Club, and Scuba Shop are all within the community. Open any card for directions in Google Maps.', 'La villa, el campo de golf, Beach Club y Scuba Shop están dentro de la comunidad. Abra cualquier tarjeta para ver las indicaciones en Google Maps.')
$homePage.Add('aria-label="Nearby Pristine Bay amenities"', 'aria-label="Amenidades cercanas en Pristine Bay"')
$homePage.Add('<small>Your villa and private pool</small>', '<small>Su villa y piscina privada</small>')
$homePage.Add('<small>18 holes through Pristine Bay</small>', '<small>18 hoyos a través de Pristine Bay</small>')
$homePage.Add('<strong>Beach Club &amp; shoreline</strong><small>Pools, beach, and Caribbean water</small>', '<strong>Beach Club y costa</strong><small>Piscinas, playa y aguas del Caribe</small>')
$homePage.Add('<small>Gear, guides, and dive experiences</small>', '<small>Equipo, guías y experiencias de buceo</small>')
$homePage.Add('<em>Directions ↗</em>', '<em>Cómo llegar ↗</em>')
$homePage.Add('Amenity access, hours, and fees may vary. Confirm current arrangements with the property manager.', 'El acceso a las amenidades, los horarios y las tarifas pueden variar. Confirme las condiciones vigentes con la administración de la propiedad.')
$homePage.Add('Plan your stay', 'Planifique su estadía')
$homePage.Add('Check availability.', 'Consulte disponibilidad.')
$homePage.Add('Select your dates to view live availability, rates, policies, payment options, and more. All booking details, scheduling, and follow-up are securely managed by Roatán Property Management.', 'Seleccione sus fechas para ver disponibilidad, tarifas, políticas, opciones de pago y más. Roatán Property Management gestiona de forma segura todos los detalles, las fechas y el seguimiento de la reservación.')
$homePage.Add('Open full booking page', 'Abrir página completa de reservación')
$homePage.Add('Contact the manager', 'Contactar a la administración')
$homePage.Add('Before you book', 'Antes de reservar')
$homePage.Add('The manager currently notes a three-night minimum, separately metered electricity, taxes, and property-specific fees. Confirm the final terms shown during booking.', 'La administración indica actualmente un mínimo de tres noches, electricidad medida por separado, impuestos y cargos específicos de la propiedad. Confirme las condiciones finales que aparezcan al reservar.')
$homePage.Add('Review manager details ↗', 'Revisar detalles de la administración ↗')
$homePage.Add('<strong>Live availability</strong>', '<strong>Disponibilidad en vivo</strong>')
$homePage.Add('>Return to calendar</button>', '>Volver al calendario</button>')
$homePage.Add('>Open separately ↗</a>', '>Abrir por separado ↗</a>')
$homePage.Add('>Loading the live calendar…</div>', '>Cargando el calendario en vivo…</div>')
$homePage.Add('title="Live availability calendar"', 'title="Calendario de disponibilidad en vivo"')
$homePage.Add('href="/pristine-bay-vacation-rental/"', 'href="/es/pristine-bay-vacation-rental/"')
$homePage.Add('href="/roatan-golf-and-diving/"', 'href="/es/roatan-golf-and-diving/"')
$homePage.Add('href="/villa-and-amenities/"', 'href="/es/villa-and-amenities/"')
$homePage.Add('href="assets/', 'href="/assets/')
$homePage.Add('src="assets/', 'src="/assets/')
$homePage.Add('srcset="assets/', 'srcset="/assets/')
$homePage.Add('poster="assets/', 'poster="/assets/')
$homePage.Add('aria-label="Full-screen property gallery"', 'aria-label="Galería de la propiedad en pantalla completa"')
$homePage.Add('aria-label="Close full-screen gallery"', 'aria-label="Cerrar galería de pantalla completa"')
$homePage.Add('aria-label="Photo zoom controls"', 'aria-label="Controles de ampliación de fotos"')
$homePage.Add('aria-label="Zoom out"', 'aria-label="Alejar"')
$homePage.Add('aria-label="Reset zoom"', 'aria-label="Restablecer ampliación"')
$homePage.Add('aria-label="Zoom in"', 'aria-label="Acercar"')
$homePage.Add('Pinch, scroll, or double-tap to zoom', 'Pellizque, desplace o toque dos veces para ampliar')
Write-SpanishPage -Source (Join-Path $publicRoot 'index.html') -Destination (Join-Path $publicRoot 'es\index.html') -Replacements $homePage

function New-LandingReplacements {
  param([string] $EnglishUrl, [string] $SpanishUrl, [string] $SpanishToggleHref)
  $map = [ordered]@{}
  foreach ($entry in $shared.GetEnumerator()) { $map.Add($entry.Key, $entry.Value) }
  $map.Add(('<link rel="canonical" href="{0}" />' -f $EnglishUrl), ('<link rel="canonical" href="{0}" />' -f $SpanishUrl))
  $map.Add(('<meta property="og:url" content="{0}" />' -f $EnglishUrl), ('<meta property="og:url" content="{0}" />' -f $SpanishUrl))
  $englishPath = ([uri] $EnglishUrl).AbsolutePath
  $map.Add(('href="{0}" hreflang="es" lang="es" data-language-switch="en"' -f $SpanishToggleHref), ('href="{0}" hreflang="en" lang="en" data-language-switch="en"' -f $englishPath))
  $map.Add(('"@id": "{0}#webpage"' -f $EnglishUrl), ('"@id": "{0}#webpage"' -f $SpanishUrl))
  $map.Add(('"url": "{0}"' -f $EnglishUrl), ('"url": "{0}"' -f $SpanishUrl))
  $map.Add(('"item": "{0}"' -f $EnglishUrl), ('"item": "{0}"' -f $SpanishUrl))
  return $map
}

$pristine = New-LandingReplacements 'https://staypristinebay.com/pristine-bay-vacation-rental/' 'https://staypristinebay.com/es/pristine-bay-vacation-rental/' '/es/pristine-bay-vacation-rental/'
$pristine.Add('<title>Pristine Bay Vacation Rental in Roatán | 1111 Pearl Court</title>', '<title>Alquiler vacacional en Pristine Bay, Roatán | 1111 Pearl Court</title>')
$pristine.Add('content="Discover a private two-suite vacation rental with an infinity pool inside gated Pristine Bay, Roatán, near the Black Pearl Golf Course and scuba diving."', 'content="Conozca una villa privada para cuatro con piscina infinita dentro de Pristine Bay, Roatán, cerca del campo de golf Black Pearl y del buceo."')
$pristine.Add('content="A Vacation Rental Inside Gated Pristine Bay, Roatán"', 'content="Alquiler vacacional dentro de Pristine Bay, Roatán"')
$pristine.Add('content="Stay close to golf, diving and the Caribbean shoreline in a private two-suite villa with an infinity pool."', 'content="Hospédese cerca del golf, el buceo y la costa caribeña en una villa privada para cuatro con piscina infinita."')
$pristine.Add('content="Villas beside the Black Pearl Golf Course in Pristine Bay, Roatán"', 'content="Villas junto al campo de golf Black Pearl en Pristine Bay, Roatán"')
$pristine.Add('content="Pristine Bay Vacation Rental in Roatán"', 'content="Alquiler vacacional en Pristine Bay, Roatán"')
$pristine.Add('content="A private two-suite villa with an infinity pool inside gated Pristine Bay."', 'content="Villa privada para cuatro con piscina infinita dentro de Pristine Bay."')
$pristine.Add('"name": "Pristine Bay Vacation Rental in Roatán"', '"name": "Alquiler vacacional en Pristine Bay, Roatán"')
$pristine.Add('"description": "A guide to staying at 1111 Pearl Court inside the gated Pristine Bay community in Roatán, Honduras."', ('"description": "Guía para hospedarse en 1111 Pearl Court dentro de la comunidad cerrada Pristine Bay en Roatán, Honduras.",' + [Environment]::NewLine + '        "inLanguage": "es-HN"'))
$pristine.Add('"name": "Pristine Bay Vacation Rental"', '"name": "Alquiler vacacional en Pristine Bay"')
$pristine.Add('aria-label="Stay Pristine Bay home"', 'aria-label="Inicio de Stay Pristine Bay"')
$pristine.Add('alt="Pristine Bay villas beside the Black Pearl Golf Course and Caribbean Sea"', 'alt="Villas de Pristine Bay junto al campo de golf Black Pearl y el mar Caribe"')
$pristine.Add('alt="Aerial view of the Black Pearl Golf Course and Caribbean coastline"', 'alt="Vista aérea del campo de golf Black Pearl y la costa caribeña"')
$pristine.Add('alt="Private infinity pool and patio at 1111 Pearl Court"', 'alt="Piscina infinita privada y terraza en 1111 Pearl Court"')
$pristine.Add('alt="Pristine Bay coastline on Roatán''s north shore"', 'alt="Costa de Pristine Bay en la zona norte de Roatán"')
$pristine.Add('alt="1111 Pearl Court villa and private pool inside Pristine Bay"', 'alt="Villa 1111 Pearl Court y piscina privada dentro de Pristine Bay"')
$pristine.Add('>Stay inside Pristine Bay</p>', '>Hospédese dentro de Pristine Bay</p>')
$pristine.Add('Gated comfort.<br />Island close by.', 'Comodidad y seguridad.<br />La isla a su alcance.')
$pristine.Add('1111 Pearl Court places four guests inside the gated Pristine Bay community, with a private infinity pool at home and golf, diving and Caribbean days waiting nearby.', '1111 Pearl Court aloja a cuatro personas dentro de la comunidad cerrada Pristine Bay, con piscina infinita privada y el golf, el buceo y el Caribe muy cerca.')
$pristine.Add('>Check availability</a>', '>Consultar disponibilidad</a>')
$pristine.Add('>Explore nearby activities</a>', '>Conocer actividades cercanas</a>')
$pristine.Add('aria-label="Stay highlights"', 'aria-label="Lo mejor de la estadía"')
$pristine.Add('<strong>Gated community</strong><span>Inside Pristine Bay</span>', '<strong>Comunidad cerrada</strong><span>Dentro de Pristine Bay</span>')
$pristine.Add('<strong>Private infinity pool</strong><span>At the villa</span>', '<strong>Piscina infinita privada</strong><span>En la villa</span>')
$pristine.Add('<strong>Two king suites</strong><span>Room for four</span>', '<strong>Dos suites con cama king</strong><span>Espacio para cuatro</span>')
$pristine.Add('<strong>Black Pearl nearby</strong><span>Golf within Pristine Bay</span>', '<strong>Black Pearl muy cerca</strong><span>Golf dentro de Pristine Bay</span>')
$pristine.Add('<p class="landing-eyebrow">The setting</p><h2>A quieter base for a full Roatán stay.</h2>', '<p class="landing-eyebrow">El entorno</p><h2>Un lugar tranquilo para disfrutar todo Roatán.</h2>')
$pristine.Add("Pristine Bay is a coastal community on Roatán’s north shore. From the villa, guests can settle into private indoor-outdoor living while staying close to the Black Pearl Golf Course, the Pristine Bay shoreline and a nearby scuba shop.", 'Pristine Bay es una comunidad costera en la zona norte de Roatán. Desde la villa, los huéspedes disfrutan espacios privados interiores y exteriores, cerca del campo de golf Black Pearl, la costa de Pristine Bay y una tienda de buceo.')
$pristine.Add('The location works especially well for travellers who want activities within easy reach without giving up a calm home base. Return from a round of golf or a day on the water to your own pool, patios, kitchen and two complete king suites.', 'La ubicación es ideal para quienes desean tener actividades a poca distancia sin renunciar a un alojamiento tranquilo. Después de una ronda de golf o un día en el mar, regrese a su propia piscina, terrazas, cocina y dos suites completas con cama king.')
$pristine.Add('<h3>Golf woven into the landscape</h3><p>The Black Pearl winds through Pristine Bay, putting the fairway close to the villa while preserving broad island and sea views.</p><a', '<h3>Golf integrado al paisaje</h3><p>Black Pearl recorre Pristine Bay, con el campo cerca de la villa y amplias vistas de la isla y el mar.</p><a')
$pristine.Add('>Visit Pristine Bay ↗</a>', '>Visitar Pristine Bay ↗</a>')
$pristine.Add('<h3>Private space between outings</h3><p>The infinity pool, shaded patios and open-plan living area give four guests room to slow down between island adventures.</p><a', '<h3>Espacio privado entre paseos</h3><p>La piscina infinita, las terrazas con sombra y la sala de concepto abierto dan a cuatro huéspedes espacio para descansar entre aventuras.</p><a')
$pristine.Add('>See villa amenities →</a>', '>Ver las comodidades de la villa →</a>')
$pristine.Add('<h3>The coast within easy reach</h3><p>Golf, diving and shoreline experiences are nearby, with more beaches, dining and island stops available across Roatán.</p><a', '<h3>La costa al alcance</h3><p>El golf, el buceo y la costa están cerca, y en toda Roatán encontrará más playas, restaurantes y lugares por conocer.</p><a')
$pristine.Add('>Plan golf and diving →</a>', '>Planificar golf y buceo →</a>')
$pristine.Add('<h2>A private villa made for four.</h2><p>Two upstairs king suites each include a full ensuite, walk-in closet and furnished private balcony. Downstairs, the kitchen, dining and living areas connect directly to the pool and patios.</p>', '<h2>Una villa privada para cuatro.</h2><p>Las dos suites con cama king del piso superior tienen baño privado completo, vestidor y balcón privado amueblado. Abajo, la cocina, el comedor y la sala se conectan directamente con la piscina y las terrazas.</p>')
$pristine.Add('>Two bedrooms</li>', '>Dos dormitorios</li>')
$pristine.Add('>Two-and-a-half bathrooms</li>', '>Dos baños y medio</li>')
$pristine.Add('>Wi-Fi and air conditioning</li>', '>Wi-Fi y aire acondicionado</li>')
$pristine.Add('>In-villa laundry</li>', '>Lavandería en la villa</li>')
$pristine.Add('Community amenities, golf, diving and other activities are arranged separately. Confirm current access, hours, reservations and fees with each provider or Roatán Property Management.', 'Las amenidades comunitarias, el golf, el buceo y otras actividades se coordinan por separado. Confirme el acceso, los horarios, las reservaciones y las tarifas vigentes con cada proveedor o con Roatán Property Management.')
$pristine.Add('Stay in Pristine Bay.<br />Explore from your front door.', 'Hospédese en Pristine Bay.<br />Explore desde su puerta.')
$pristine.Add('View live dates through the embedded manager calendar, then complete booking details securely with Roatán Property Management.', 'Consulte las fechas disponibles en el calendario de la administración y luego complete los detalles de la reservación de forma segura con Roatán Property Management.')
$pristine.Add('>View live availability</a>', '>Ver disponibilidad en vivo</a>')
$pristine.Add('>Contact the manager ↗</a>', '>Contactar a la administración ↗</a>')
$pristine.Add('href="/"', 'href="/es/"')
$pristine.Add('href="/#', 'href="/es/#')
$pristine.Add('href="/roatan-golf-and-diving/"', 'href="/es/roatan-golf-and-diving/"')
$pristine.Add('href="/pristine-bay-vacation-rental/"', 'href="/es/pristine-bay-vacation-rental/"')
$pristine.Add('href="/villa-and-amenities/"', 'href="/es/villa-and-amenities/"')
$pristine.Add('href="/es/pristine-bay-vacation-rental/" hreflang="en" lang="en" data-language-switch="en"', 'href="/pristine-bay-vacation-rental/" hreflang="en" lang="en" data-language-switch="en"')
Write-SpanishPage -Source (Join-Path $publicRoot 'pristine-bay-vacation-rental\index.html') -Destination (Join-Path $publicRoot 'es\pristine-bay-vacation-rental\index.html') -Replacements $pristine

$golf = New-LandingReplacements 'https://staypristinebay.com/roatan-golf-and-diving/' 'https://staypristinebay.com/es/roatan-golf-and-diving/' '/es/roatan-golf-and-diving/'
$golf.Add('<title>Roatán Golf and Diving Near Pristine Bay | Stay Guide</title>', '<title>Golf y buceo en Roatán cerca de Pristine Bay | Guía</title>')
$golf.Add('content="Plan golf at the Black Pearl and scuba diving near Pristine Bay from 1111 Pearl Court, with beaches, dining and Roatán day ideas nearby."', 'content="Planifique golf en Black Pearl y buceo cerca de Pristine Bay desde 1111 Pearl Court, además de playas, restaurantes y paseos por Roatán."')
$golf.Add('content="Golf, Diving and Island Days Near Pristine Bay"', 'content="Golf, buceo y días de isla cerca de Pristine Bay"')
$golf.Add('content="Stay close to the Black Pearl Golf Course, a nearby scuba shop and more Roatán experiences."', 'content="Hospédese cerca del campo de golf Black Pearl, una tienda de buceo y más experiencias en Roatán."')
$golf.Add('content="The Black Pearl Golf Course beside the Caribbean Sea in Pristine Bay"', 'content="El campo de golf Black Pearl junto al mar Caribe en Pristine Bay"')
$golf.Add('content="Roatán Golf and Diving Near Pristine Bay"', 'content="Golf y buceo en Roatán cerca de Pristine Bay"')
$golf.Add('content="A practical guide to golf, diving and nearby island experiences from 1111 Pearl Court."', 'content="Guía práctica de golf, buceo y experiencias cercanas en la isla desde 1111 Pearl Court."')
$golf.Add('"name": "Roatán Golf and Diving Near Pristine Bay"', '"name": "Golf y buceo en Roatán cerca de Pristine Bay"')
$golf.Add('"description": "A visitor guide to golf, scuba diving and nearby activities while staying at 1111 Pearl Court in Pristine Bay."', ('"description": "Guía para visitantes sobre golf, buceo y actividades cercanas durante una estadía en 1111 Pearl Court en Pristine Bay.",' + [Environment]::NewLine + '        "inLanguage": "es-HN"'))
$golf.Add('"name": "Scuba diving in Roatán"', '"name": "Buceo en Roatán"')
$golf.Add('"name": "Roatán Golf and Diving"', '"name": "Golf y buceo en Roatán"')
$golf.Add('aria-label="Stay Pristine Bay home"', 'aria-label="Inicio de Stay Pristine Bay"')
$golf.Add('alt="Black Pearl Golf Course fairway overlooking the Caribbean Sea"', 'alt="Campo de golf Black Pearl con vista al mar Caribe"')
$golf.Add('alt="Black Pearl Golf Course fairway through the hills of Pristine Bay"', 'alt="Campo de golf Black Pearl entre las colinas de Pristine Bay"')
$golf.Add('alt="Scuba diver exploring coral reef in clear Caribbean water"', 'alt="Buzo explorando un arrecife en aguas cristalinas del Caribe"')
$golf.Add('alt="Pool and Caribbean shoreline at Pristine Bay"', 'alt="Piscina y costa caribeña en Pristine Bay"')
$golf.Add('alt="Aerial coastline and green hills around Pristine Bay, Roatán"', 'alt="Vista aérea de la costa y las colinas verdes alrededor de Pristine Bay, Roatán"')
$golf.Add('alt="Island dining table with food and ocean view"', 'alt="Mesa con comida isleña y vista al mar"')
$golf.Add('alt="Craft beer served at a brewery"', 'alt="Cerveza artesanal servida en una cervecería"')
$golf.Add('alt="Colourful macaws at a Roatán attraction"', 'alt="Guacamayas coloridas en una atracción de Roatán"')
$golf.Add('Golf · dive · explore', 'Golf · buceo · aventura')
$golf.Add('More island.<br />Less planning.', 'Más isla.<br />Menos planificación.')
$golf.Add('Base your Roatán stay beside the Black Pearl Golf Course and near a scuba shop, then build the rest of your days around beaches, dining and island stops.', 'Hospédese en Roatán junto al campo de golf Black Pearl y cerca de una tienda de buceo; luego complete sus días con playas, restaurantes y paseos por la isla.')
$golf.Add('>Open the activities map</a>', '>Abrir el mapa de actividades</a>')
$golf.Add('>Check availability</a>', '>Consultar disponibilidad</a>')
$golf.Add('aria-label="Nearby activities"', 'aria-label="Actividades cercanas"')
$golf.Add('<strong>Championship golf</strong><span>Black Pearl in Pristine Bay</span>', '<strong>Golf de campeonato</strong><span>Black Pearl en Pristine Bay</span>')
$golf.Add('<strong>Scuba diving</strong><span>Shop and training nearby</span>', '<strong>Buceo</strong><span>Tienda y capacitación cerca</span>')
$golf.Add('<strong>Caribbean beaches</strong><span>Explore across Roatán</span>', '<strong>Playas del Caribe</strong><span>Explore toda Roatán</span>')
$golf.Add('<strong>Island dining</strong><span>Casual through special occasion</span>', '<strong>Gastronomía isleña</strong><span>Desde algo casual hasta ocasiones especiales</span>')
$golf.Add('<p class="landing-eyebrow">Close to home</p><h2>Two signature Roatán experiences nearby.</h2>', '<p class="landing-eyebrow">Muy cerca</p><h2>Dos experiencias emblemáticas de Roatán.</h2>')
$golf.Add('Golf and diving shape an easy day at Pristine Bay. The Black Pearl runs through the community, while the nearby Scuba Shop offers a direct starting point for gear, training and dive experiences.', 'El golf y el buceo forman parte de un día perfecto en Pristine Bay. Black Pearl atraviesa la comunidad, mientras Scuba Shop ofrece equipo, capacitación y experiencias de buceo muy cerca.')
$golf.Add('Reservations, equipment, certifications, conditions and fees are handled by the individual providers. Check current details directly before building them into your stay.', 'Cada proveedor gestiona sus reservaciones, equipo, certificaciones, condiciones y tarifas. Consulte los detalles vigentes directamente antes de incluir estas actividades en su estadía.')
$golf.Add('<h3>Play the Black Pearl</h3><p>Plan a morning round through Pristine Bay, then return to the villa for lunch, a swim and a quiet afternoon.</p>', '<h3>Juegue en Black Pearl</h3><p>Disfrute una ronda matutina en Pristine Bay y luego regrese a la villa para almorzar, nadar y pasar una tarde tranquila.</p>')
$golf.Add('>Explore the golf course ↗</a>', '>Conocer el campo de golf ↗</a>')
$golf.Add("<h3>Dive Roatán’s clear water</h3><p>Connect with a nearby dive operator for training, guided dives, snorkelling information and current water conditions.</p>", '<h3>Sumérjase en las aguas cristalinas de Roatán</h3><p>Comuníquese con un operador cercano para capacitación, buceos guiados, información sobre esnórquel y condiciones actuales del mar.</p>')
$golf.Add('>Visit the Scuba Shop ↗</a>', '>Visitar Scuba Shop ↗</a>')
$golf.Add('<h3>Leave room for the shoreline</h3><p>Balance activity days with time near the water or use the villa as a starting point for beaches elsewhere on the island.</p>', '<h3>Reserve tiempo para la costa</h3><p>Combine los días activos con tiempo junto al mar o use la villa como punto de partida para conocer otras playas de la isla.</p>')
$golf.Add('>Explore Roatán beaches ↗</a>', '>Conocer las playas de Roatán ↗</a>')
$golf.Add('<p class="landing-eyebrow">A flexible island day</p><h2>Start nearby. Follow the island from there.</h2>', '<p class="landing-eyebrow">Un día flexible en la isla</p><h2>Comience cerca. Siga explorando la isla.</h2>')
$golf.Add('A practical day can begin with golf or a dive close to the villa, continue with lunch or beach time, and finish with a relaxed evening back at the private pool. On another day, head farther west for beaches and dining or add a family-friendly island attraction.', 'Un buen día puede comenzar con golf o buceo cerca de la villa, continuar con almuerzo o tiempo en la playa y terminar con una tarde tranquila en la piscina privada. Otro día, vaya hacia el oeste para conocer playas y restaurantes o visite una atracción para toda la familia.')
$golf.Add('>Morning round or dive</li>', '>Golf o buceo por la mañana</li>')
$golf.Add('>Lunch near the water</li>', '>Almuerzo cerca del mar</li>')
$golf.Add('>West End or West Bay outing</li>', '>Paseo a West End o West Bay</li>')
$golf.Add('>Sunset by the villa pool</li>', '>Atardecer junto a la piscina</li>')
$golf.Add('Travel times, access, reservations and availability vary. Confirm details with providers and allow extra time for island traffic.', 'Los tiempos de viaje, el acceso, las reservaciones y la disponibilidad varían. Confirme los detalles con los proveedores y considere tiempo adicional por el tráfico de la isla.')
$golf.Add('<p class="landing-eyebrow">More to explore</p><h2>Dining, local flavour and easy stops.</h2>', '<p class="landing-eyebrow">Más por conocer</p><h2>Gastronomía, sabor local y paradas sencillas.</h2>')
$golf.Add('Roatán offers everything from casual roadside food to dining with ocean views. If you want to sample local craft beer, Roatán Island Brewing Company is another possible island stop. Groceries, shops and tour providers can also be worked into a day away from the villa.', 'Roatán ofrece desde comida informal a la orilla del camino hasta restaurantes con vista al mar. Para probar cerveza artesanal local, puede visitar Roatán Island Brewing Company. También puede incluir supermercados, tiendas y operadores turísticos en un día fuera de la villa.')
$golf.Add('Use the activities map for an overview, then confirm hours and directions with each business before leaving.', 'Use el mapa de actividades como guía y confirme los horarios y las indicaciones con cada negocio antes de salir.')
$golf.Add('<h3>Find a meal that fits the day</h3><p>Search around Pristine Bay or make dining part of a larger outing toward West End and West Bay.</p>', '<h3>Encuentre la comida ideal para el día</h3><p>Busque cerca de Pristine Bay o incluya un restaurante en un paseo más largo hacia West End y West Bay.</p>')
$golf.Add('>Explore restaurants ↗</a>', '>Explorar restaurantes ↗</a>')
$golf.Add('<h3>Try a local brewery</h3><p>Check current opening hours, food options and directions before adding a brewery stop to your island route.</p>', '<h3>Pruebe una cervecería local</h3><p>Revise los horarios, las opciones de comida y las indicaciones antes de incluir una cervecería en su ruta por la isla.</p>')
$golf.Add('>Visit Roatán Island Brewing ↗</a>', '>Visitar Roatán Island Brewing ↗</a>')
$golf.Add('<h3>Add an island attraction</h3><p>Botanical gardens, wildlife experiences and tours can turn an open afternoon into a memorable stop.</p>', '<h3>Agregue una atracción de la isla</h3><p>Jardines botánicos, experiencias con fauna y tours pueden convertir una tarde libre en un recuerdo especial.</p>')
$golf.Add('>View the activities page →</a>', '>Ver la página de actividades →</a>')
$golf.Add('Come for the villa.<br />Book for the island.', 'Venga por la villa.<br />Reserve por la isla.')
$golf.Add('Stay close to signature activities while keeping a private pool, full kitchen and two king suites as your home base.', 'Hospédese cerca de actividades emblemáticas y disfrute una piscina privada, cocina completa y dos suites con cama king como su espacio en la isla.')
$golf.Add('>View live availability</a>', '>Ver disponibilidad en vivo</a>')
$golf.Add('>See the Pristine Bay setting</a>', '>Conocer el entorno de Pristine Bay</a>')
$golf.Add('href="/"', 'href="/es/"')
$golf.Add('href="/#', 'href="/es/#')
$golf.Add('href="/roatan-golf-and-diving/"', 'href="/es/roatan-golf-and-diving/"')
$golf.Add('href="/pristine-bay-vacation-rental/"', 'href="/es/pristine-bay-vacation-rental/"')
$golf.Add('href="/villa-and-amenities/"', 'href="/es/villa-and-amenities/"')
$golf.Add('href="/es/roatan-golf-and-diving/" hreflang="en" lang="en" data-language-switch="en"', 'href="/roatan-golf-and-diving/" hreflang="en" lang="en" data-language-switch="en"')
Write-SpanishPage -Source (Join-Path $publicRoot 'roatan-golf-and-diving\index.html') -Destination (Join-Path $publicRoot 'es\roatan-golf-and-diving\index.html') -Replacements $golf

$villa = New-LandingReplacements 'https://staypristinebay.com/villa-and-amenities/' 'https://staypristinebay.com/es/villa-and-amenities/' '/es/villa-and-amenities/'
$villa.Add('<title>Roatán Villa with Private Pool | Amenities at 1111 Pearl Court</title>', '<title>Villa en Roatán con piscina privada | 1111 Pearl Court</title>')
$villa.Add('content="Tour the two king suites, private infinity pool, patios, full kitchen and everyday amenities at 1111 Pearl Court in Pristine Bay, Roatán."', 'content="Conozca las dos suites con cama king, piscina infinita privada, terrazas, cocina completa y comodidades de 1111 Pearl Court en Pristine Bay, Roatán."')
$villa.Add('content="A Two-Suite Roatán Villa with a Private Infinity Pool"', 'content="Villa en Roatán con dos suites y piscina infinita privada"')
$villa.Add('content="See the sleeping spaces, indoor-outdoor living and practical amenities at 1111 Pearl Court."', 'content="Conozca los dormitorios, los espacios interiores y exteriores y las comodidades prácticas de 1111 Pearl Court."')
$villa.Add('content="1111 Pearl Court villa and private infinity pool in Pristine Bay, Roatán"', 'content="Villa 1111 Pearl Court y piscina infinita privada en Pristine Bay, Roatán"')
$villa.Add('content="Roatán Villa with Private Pool and Two King Suites"', 'content="Villa en Roatán con piscina privada y dos suites con cama king"')
$villa.Add('content="Explore the villa, pool, patios, kitchen and everyday amenities at 1111 Pearl Court."', 'content="Conozca la villa, piscina, terrazas, cocina y comodidades de 1111 Pearl Court."')
$villa.Add('"name": "Villa and Amenities at 1111 Pearl Court"', '"name": "Villa y comodidades en 1111 Pearl Court"')
$villa.Add('"description": "A detailed guide to the suites, pool, patios, kitchen and amenities at 1111 Pearl Court in Pristine Bay, Roatán."', ('"description": "Guía detallada de las suites, piscina, terrazas, cocina y comodidades de 1111 Pearl Court en Pristine Bay, Roatán.",' + [Environment]::NewLine + '        "inLanguage": "es-HN"'))
$villa.Add('"name": "Villa and Amenities"', '"name": "Villa y comodidades"')
$villa.Add('aria-label="Stay Pristine Bay home"', 'aria-label="Inicio de Stay Pristine Bay"')
$villa.Add('alt="Aerial view of 1111 Pearl Court and its private infinity pool"', 'alt="Vista aérea de 1111 Pearl Court y su piscina infinita privada"')
$villa.Add('alt="Primary king bedroom with windows and tropical views"', 'alt="Dormitorio principal con cama king, ventanas y vistas tropicales"')
$villa.Add('alt="Private infinity pool surrounded by tropical landscaping"', 'alt="Piscina infinita privada rodeada de jardines tropicales"')
$villa.Add('alt="Covered patio and seating beside the villa pool"', 'alt="Terraza techada con asientos junto a la piscina de la villa"')
$villa.Add('alt="Dining space beside the private pool"', 'alt="Comedor junto a la piscina privada"')
$villa.Add('alt="Fully equipped open-plan kitchen at 1111 Pearl Court"', 'alt="Cocina de concepto abierto totalmente equipada en 1111 Pearl Court"')
$villa.Add('alt="Open-plan living room with doors toward the pool"', 'alt="Sala de concepto abierto con puertas hacia la piscina"')
$villa.Add('alt="Guest king bedroom opening to a private terrace"', 'alt="Dormitorio de huéspedes con cama king y acceso a una terraza privada"')
$villa.Add('alt="Tropical garden surrounding 1111 Pearl Court"', 'alt="Jardín tropical alrededor de 1111 Pearl Court"')
$villa.Add('The villa at 1111 Pearl Court', 'La villa en 1111 Pearl Court')
$villa.Add('Space to settle.<br />Easy to enjoy.', 'Espacio para descansar.<br />Fácil de disfrutar.')
$villa.Add('A private Roatán villa for four with two complete king suites, an infinity pool and indoor-outdoor spaces designed for unhurried island days.', 'Una villa privada en Roatán para cuatro personas, con dos suites completas con cama king, piscina infinita y espacios interiores y exteriores para disfrutar la isla sin prisa.')
$villa.Add('>View the full gallery</a>', '>Ver la galería completa</a>')
$villa.Add('>Check availability</a>', '>Consultar disponibilidad</a>')
$villa.Add('aria-label="Villa capacity"', 'aria-label="Capacidad de la villa"')
$villa.Add('<strong>Two bedrooms</strong><span>Both with king beds</span>', '<strong>Dos dormitorios</strong><span>Ambos con cama king</span>')
$villa.Add('<strong>2½ bathrooms</strong><span>Two ensuites plus powder room</span>', '<strong>2½ baños</strong><span>Dos baños privados y un medio baño</span>')
$villa.Add('<strong>Four guests</strong><span>Private villa stay</span>', '<strong>Cuatro huéspedes</strong><span>Estadía en villa privada</span>')
$villa.Add('<strong>Infinity pool</strong><span>Private pool and patios</span>', '<strong>Piscina infinita</strong><span>Piscina y terrazas privadas</span>')
$villa.Add('<p class="landing-eyebrow">Sleep well</p><h2>Two complete king suites.</h2><p>Each upstairs bedroom is arranged as a private suite with a king bed, full ensuite bathroom, walk-in closet and furnished balcony. The layout gives two couples or a family of four comfortable personal space while keeping everyone together under one roof.</p>', '<p class="landing-eyebrow">Descanse bien</p><h2>Dos suites completas con cama king.</h2><p>Cada dormitorio del piso superior es una suite privada con cama king, baño completo, vestidor y balcón amueblado. La distribución ofrece espacio personal para dos parejas o una familia de cuatro, bajo un mismo techo.</p>')
$villa.Add('>King bed in each suite</li>', '>Cama king en cada suite</li>')
$villa.Add('>Private full ensuite</li>', '>Baño completo privado</li>')
$villa.Add('>Walk-in closet</li>', '>Vestidor</li>')
$villa.Add('>Furnished private balcony</li>', '>Balcón privado amueblado</li>')
$villa.Add('>Browse bedroom photos ', '>Ver fotos de los dormitorios ')
$villa.Add('<p class="landing-eyebrow">Live inside and out</p><h2>The pool is part of the floor plan.</h2>', '<p class="landing-eyebrow">Disfrute adentro y afuera</p><h2>La piscina es parte de la vida diaria.</h2>')
$villa.Add('The main level opens directly toward the private infinity pool and several outdoor areas. Move easily between the kitchen, dining table, living room, shaded patios and pool deck without losing the relaxed flow of the day.', 'La planta principal se abre directamente hacia la piscina infinita privada y varios espacios exteriores. Pase con facilidad entre la cocina, el comedor, la sala, las terrazas con sombra y el área de piscina, sin perder el ritmo relajado del día.')
$villa.Add('There is room for a quiet morning coffee, an afternoon swim, outdoor dining and a comfortable evening back at the villa.', 'Hay espacio para un café tranquilo por la mañana, un baño por la tarde, una cena al aire libre y una noche cómoda en la villa.')
$villa.Add('<h3>Your own infinity pool</h3><p>Swim or unwind without leaving the villa, with the pool set directly beside the main living spaces.</p>', '<h3>Su propia piscina infinita</h3><p>Nade o relájese sin salir de la villa; la piscina está junto a los espacios principales.</p>')
$villa.Add('>See pool photos →</a>', '>Ver fotos de la piscina →</a>')
$villa.Add('<h3>Shade when you want it</h3><p>Covered patio areas keep the outdoor space useful for meals, conversation and breaks from the midday sun.</p>', '<h3>Sombra cuando la quiera</h3><p>Las terrazas techadas permiten comer, conversar y descansar del sol del mediodía.</p>')
$villa.Add('>See outdoor living →</a>', '>Ver espacios exteriores →</a>')
$villa.Add('<h3>Meals beside the pool</h3><p>The indoor and outdoor dining areas let you choose between air-conditioned comfort and a tropical evening outside.</p>', '<h3>Comidas junto a la piscina</h3><p>Los comedores interior y exterior permiten elegir entre el aire acondicionado y una noche tropical al aire libre.</p>')
$villa.Add('>Browse the complete gallery →</a>', '>Ver la galería completa →</a>')
$villa.Add('<p class="landing-eyebrow">Everyday comfort</p><h2>A real kitchen and the practical details.</h2>', '<p class="landing-eyebrow">Comodidad diaria</p><h2>Una cocina completa y detalles prácticos.</h2>')
$villa.Add('The open kitchen provides the appliances and work space needed for breakfast, snacks or a full meal. Wi-Fi, air conditioning, televisions and laundry help longer stays feel straightforward, while the main-level powder room keeps the upstairs ensuites private.', 'La cocina abierta ofrece los electrodomésticos y el espacio necesarios para preparar desde el desayuno hasta una comida completa. El Wi-Fi, aire acondicionado, televisores y lavandería facilitan las estadías más largas, mientras el medio baño de la planta principal mantiene privados los baños de arriba.')
$villa.Add('>Fully equipped kitchen</li>', '>Cocina totalmente equipada</li>')
$villa.Add('>Air conditioning</li>', '>Aire acondicionado</li>')
$villa.Add('>Wi-Fi and televisions</li>', '>Wi-Fi y televisores</li>')
$villa.Add('>Laundry appliances</li>', '>Equipo de lavandería</li>')
$villa.Add('Specific supplies, appliances, minimum stays and booking terms can change. Confirm current details with Roatán Property Management before arrival.', 'Los suministros, electrodomésticos, estadías mínimas y condiciones de reservación pueden cambiar. Confirme los detalles vigentes con Roatán Property Management antes de llegar.')
$villa.Add('<p class="landing-eyebrow">At a glance</p><h2>What the villa gives your stay.</h2>', '<p class="landing-eyebrow">En resumen</p><h2>Lo que la villa aporta a su estadía.</h2>')
$villa.Add('1111 Pearl Court is designed as a self-contained home base rather than a hotel room. Four guests can spend time together in the open living areas and still retreat to private suites and balconies.', '1111 Pearl Court es una casa completa, no una habitación de hotel. Cuatro huéspedes pueden compartir los espacios abiertos y también descansar en suites y balcones privados.')
$villa.Add('Its Pristine Bay location adds a gated community setting and nearby golf and diving, while the villa itself supplies the private pool and everyday comforts that make downtime part of the vacation.', 'Su ubicación en Pristine Bay ofrece una comunidad cerrada con golf y buceo cercanos, mientras la villa brinda la piscina privada y las comodidades diarias que hacen del descanso parte de las vacaciones.')
$villa.Add('<h3>Open main level</h3><p>Living, dining and kitchen areas connect naturally, with wide doors leading toward the pool and patios.</p>', '<h3>Planta principal abierta</h3><p>La sala, el comedor y la cocina se conectan naturalmente, con puertas amplias hacia la piscina y las terrazas.</p>')
$villa.Add('<h3>Two private retreats</h3><p>Both king suites include the same essential comforts, so neither pair of guests is treated like an afterthought.</p>', '<h3>Dos espacios privados</h3><p>Ambas suites con cama king tienen las mismas comodidades esenciales para que todos los huéspedes se sientan bien atendidos.</p>')
$villa.Add('<h3>Tropical surroundings</h3><p>Landscaping, patios and the pool create a private-feeling outdoor setting within gated Pristine Bay.</p>', '<h3>Entorno tropical</h3><p>Los jardines, las terrazas y la piscina crean un ambiente exterior privado dentro de Pristine Bay.</p>')
$villa.Add('See the spaces.<br />Then choose your dates.', 'Conozca los espacios.<br />Luego elija sus fechas.')
$villa.Add('Explore the full property gallery before opening the live availability calendar managed by Roatán Property Management.', 'Explore la galería completa antes de abrir el calendario de disponibilidad en vivo administrado por Roatán Property Management.')
$villa.Add('>Open the gallery</a>', '>Abrir la galería</a>')
$villa.Add('>View live availability</a>', '>Ver disponibilidad en vivo</a>')
$villa.Add('href="/"', 'href="/es/"')
$villa.Add('href="/#', 'href="/es/#')
$villa.Add('href="/roatan-golf-and-diving/"', 'href="/es/roatan-golf-and-diving/"')
$villa.Add('href="/pristine-bay-vacation-rental/"', 'href="/es/pristine-bay-vacation-rental/"')
$villa.Add('href="/villa-and-amenities/"', 'href="/es/villa-and-amenities/"')
$villa.Add('href="/es/villa-and-amenities/" hreflang="en" lang="en" data-language-switch="en"', 'href="/villa-and-amenities/" hreflang="en" lang="en" data-language-switch="en"')
Write-SpanishPage -Source (Join-Path $publicRoot 'villa-and-amenities\index.html') -Destination (Join-Path $publicRoot 'es\villa-and-amenities\index.html') -Replacements $villa

Write-Output 'Spanish pages generated.'
